### PR TITLE
README.md created

### PR DESCRIPTION
**Pull request by abirbhattacharya82**
# Issue Number:
#1 
--------------------------------------------------------
# Issue:
Adding a README.md file so that people can understand what the Repository is about.
---------------------------------------------------------
# Checklist:
- [x] Testing
- [ ] Documentation
- [x] Issue Resolved
- [x] Rules and Guidelines maintained
----------------------------------------------------------
# Screenshot:
Untitled
------------------------------------------------------------

### CODE REVIEW

**Comment by nimit2801** [comment]
Thanks for submitting this PR @abirbhattacharya82.
I'll add @Veershah26 reviewer and he can help you any further changes.

**Comment by abirbhattacharya82** [comment]
Okay, Thank You.

**Comment by Veershah26** [comment]
Hey @abirbhattacharya82. So I checked the readme files, It looks great, just a few changes. There is a typo on line 1 in the spelling on "Exercise". Also in the description of program1, kindly replace the word compiler with Interpreter, in, "With every guess the compiler will tell whether the guess is higher than or lower than the expected value.".

**Comment by abirbhattacharya82** [comment]
ok on it 👍

**Pull request closed without merging**
